server:
  port: 9191

spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: STUDENT-SERVICE
          uri: lb://STUDENT-SERVICE
          predicates:
            - Path=/api/student/**
        - id: FEES-SERVICE
          uri: lb://FEES-SERVICE
          predicates:
            - Path=/api/fees/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/