server:
  port: 9090
spring:
  application:
    name: STUDENT-SERVICE
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/studentdb
    username: sa
    password:
    platform: h2
  h2:
    console:
      enabled: true
      path: /h2-ui

# for Spring Data JPA
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#Application start publish data to Zipkin
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411/